networks:
  public_network:
    driver: bridge
    name: public_network

services:
  # Dummy service to create the shared public network
  network-creator:
    image: alpine:latest
    command: "true"
    networks:
      - public_network