version: '3.8'

services:
  service2:
    build: ./service2
    container_name: service2
    environment:
      - SERVICE_NAME=service2
      - PUBLIC_PORT=8080
      - PRIVATE_PORT=8081
    ports:
      - "8002:8080"  # Public port mapping
    networks:
      - public_network
      - service2_private
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

networks:
  public_network:
    external: true
  service2_private:
    external: true