version: '3.8'

networks:
  public_network:
    driver: bridge
    name: public_network
  
  service1_private:
    driver: bridge
    name: service1_private
  
  service2_private:
    driver: bridge
    name: service2_private
    
  service3_private:
    driver: bridge
    name: service3_private