
services:
  service3:
    build: ./service3
    container_name: service3
    environment:
      - SERVICE_NAME=service3
      - PUBLIC_PORT=8080
      - PRIVATE_PORT=8081
      - APP_MODE=public
    ports:
      - "8003:8080"  # Public port mapping
    networks:
      - public_network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  service3-private:
    build: ./service3
    container_name: service3-private
    environment:
      - SERVICE_NAME=service3
      - PUBLIC_PORT=8080
      - PRIVATE_PORT=8081
      - APP_MODE=private
    networks:
      - service3_private
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

networks:
  public_network:
    external: true
    name: public_network
  service3_private:
    external: true
    name: service3_private